/**
 * eHelply SDK - 1.1.71
 * eHelply SDK for SuperStack Services
 *
 * OpenAPI spec version: 1.1.71
 * Contact: support@ehelply.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Payment } from './Payment';
import { HttpFile } from '../http/http';

export class BodyProcessPaymentBillingProcessPaymentPost {
    'paymentSchema': Payment;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "paymentSchema",
            "baseName": "payment_schema",
            "type": "Payment",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return BodyProcessPaymentBillingProcessPaymentPost.attributeTypeMap;
    }

    public constructor() {
    }
}

