/**
 * eHelply SDK - 1.1.71
 * eHelply SDK for SuperStack Services
 *
 * OpenAPI spec version: 1.1.71
 * Contact: support@ehelply.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CategoryBase } from './CategoryBase';
import { ContactBase } from './ContactBase';
import { PlaceBase } from './PlaceBase';
import { TagBase } from './TagBase';
import { HttpFile } from '../http/http';

/**
* **:param** name                                **type:** string **:param** summary                             **type:** string or None  **:param** public                              **type:** bool or None  **:param** meta                                **type:** dict or None  **:param** contact                             **type:** ContactBase or None
*/
export class CompanyResponse {
    'name'?: string;
    'summary'?: string;
    '_public'?: boolean;
    'meta'?: any;
    'contact'?: ContactBase;
    'uuid': string;
    'projectUuid'?: string;
    'metaUuid'?: string;
    'catalogData'?: any;
    'reviewGroupData'?: any;
    'scheduleData'?: any;
    'blogData'?: any;
    'tags'?: Array<TagBase>;
    'categories'?: Array<CategoryBase>;
    'places'?: Array<PlaceBase>;
    'createdAt'?: string;
    'updatedAt'?: string;
    'deletedAt'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "summary",
            "baseName": "summary",
            "type": "string",
            "format": ""
        },
        {
            "name": "_public",
            "baseName": "public",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "meta",
            "baseName": "meta",
            "type": "any",
            "format": ""
        },
        {
            "name": "contact",
            "baseName": "contact",
            "type": "ContactBase",
            "format": ""
        },
        {
            "name": "uuid",
            "baseName": "uuid",
            "type": "string",
            "format": ""
        },
        {
            "name": "projectUuid",
            "baseName": "project_uuid",
            "type": "string",
            "format": ""
        },
        {
            "name": "metaUuid",
            "baseName": "meta_uuid",
            "type": "string",
            "format": ""
        },
        {
            "name": "catalogData",
            "baseName": "catalog_data",
            "type": "any",
            "format": ""
        },
        {
            "name": "reviewGroupData",
            "baseName": "review_group_data",
            "type": "any",
            "format": ""
        },
        {
            "name": "scheduleData",
            "baseName": "schedule_data",
            "type": "any",
            "format": ""
        },
        {
            "name": "blogData",
            "baseName": "blog_data",
            "type": "any",
            "format": ""
        },
        {
            "name": "tags",
            "baseName": "tags",
            "type": "Array<TagBase>",
            "format": ""
        },
        {
            "name": "categories",
            "baseName": "categories",
            "type": "Array<CategoryBase>",
            "format": ""
        },
        {
            "name": "places",
            "baseName": "places",
            "type": "Array<PlaceBase>",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "string",
            "format": ""
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "string",
            "format": ""
        },
        {
            "name": "deletedAt",
            "baseName": "deleted_at",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CompanyResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

