/**
 * eHelply SDK - 1.1.70
 * eHelply SDK for SuperStack Services
 *
 * OpenAPI spec version: 1.1.70
 * Contact: support@ehelply.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Options } from './Options';
import { Validations } from './Validations';
import { HttpFile } from '../http/http';

/**
* Field Dynamo
*/
export class FieldDynamo {
    'uuid': string;
    'type'?: number;
    'placeholder'?: string;
    'validations'?: Validations;
    'hint'?: string;
    'icon'?: string;
    'label'?: string;
    'options'?: Options;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "uuid",
            "baseName": "uuid",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "number",
            "format": ""
        },
        {
            "name": "placeholder",
            "baseName": "placeholder",
            "type": "string",
            "format": ""
        },
        {
            "name": "validations",
            "baseName": "validations",
            "type": "Validations",
            "format": ""
        },
        {
            "name": "hint",
            "baseName": "hint",
            "type": "string",
            "format": ""
        },
        {
            "name": "icon",
            "baseName": "icon",
            "type": "string",
            "format": ""
        },
        {
            "name": "label",
            "baseName": "label",
            "type": "string",
            "format": ""
        },
        {
            "name": "options",
            "baseName": "options",
            "type": "Options",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return FieldDynamo.attributeTypeMap;
    }

    public constructor() {
    }
}

