/**
 * eHelply SDK - 1.1.70
 * eHelply SDK for SuperStack Services
 *
 * OpenAPI spec version: 1.1.70
 * Contact: support@ehelply.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CustomList } from './CustomList';
import { HttpFile } from '../http/http';

export class MetaCustom {
    'name'?: string;
    'description'?: string;
    'list'?: Array<CustomList>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "list",
            "baseName": "list",
            "type": "Array<CustomList>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return MetaCustom.attributeTypeMap;
    }

    public constructor() {
    }
}

