/**
 * eHelply SDK - 1.1.71
 * eHelply SDK for SuperStack Services
 *
 * OpenAPI spec version: 1.1.71
 * Contact: support@ehelply.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* **:param** name                                **type:** string **:param** project_uuid                        **type:** string or None
*/
export class TagBase {
    'name': string;
    'projectUuid'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "projectUuid",
            "baseName": "project_uuid",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TagBase.attributeTypeMap;
    }

    public constructor() {
    }
}

