/* tslint:disable */
/* eslint-disable */
/**
 * eHelply SDK - 1.1.74
 * eHelply SDK for SuperStack Services
 *
 * The version of the OpenAPI document: 1.1.74
 * Contact: support@ehelply.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    HTTPValidationError,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models';

export interface GetLogsLoggingLogsGetRequest {
    service?: string;
    dateStart?: string;
    dateEnd?: string;
    desc?: boolean;
    xAccessToken?: string;
    xSecretToken?: string;
    authorization?: string;
    ehelplyActiveParticipant?: string;
    ehelplyProject?: string;
    ehelplyData?: string;
}

export interface GetServiceLogsLoggingLogsServicesServiceGetRequest {
    service: string;
    dateStart?: string;
    dateEnd?: string;
    desc?: boolean;
    limit?: number;
    xAccessToken?: string;
    xSecretToken?: string;
    authorization?: string;
    ehelplyActiveParticipant?: string;
    ehelplyProject?: string;
    ehelplyData?: string;
}

export interface GetSubjectLogsLoggingLogsServicesServiceSubjectsSubjectGetRequest {
    service: string;
    subject: string;
    dateStart?: string;
    dateEnd?: string;
    desc?: boolean;
    limit?: number;
    xAccessToken?: string;
    xSecretToken?: string;
    authorization?: string;
    ehelplyActiveParticipant?: string;
    ehelplyProject?: string;
    ehelplyData?: string;
}

/**
 * LoggingApi - interface
 * 
 * @export
 * @interface LoggingApiInterface
 */
export interface LoggingApiInterface {
    /**
     * 
     * @summary Get Logs
     * @param {string} [service] 
     * @param {string} [dateStart] 
     * @param {string} [dateEnd] 
     * @param {boolean} [desc] 
     * @param {string} [xAccessToken] 
     * @param {string} [xSecretToken] 
     * @param {string} [authorization] 
     * @param {string} [ehelplyActiveParticipant] 
     * @param {string} [ehelplyProject] 
     * @param {string} [ehelplyData] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LoggingApiInterface
     */
    getLogsLoggingLogsGetRaw(requestParameters: GetLogsLoggingLogsGetRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<any>>;

    /**
     * Get Logs
     */
    getLogsLoggingLogsGet(requestParameters: GetLogsLoggingLogsGetRequest, initOverrides?: RequestInit): Promise<any>;

    /**
     * 
     * @summary Get Service Logs
     * @param {string} service 
     * @param {string} [dateStart] 
     * @param {string} [dateEnd] 
     * @param {boolean} [desc] 
     * @param {number} [limit] 
     * @param {string} [xAccessToken] 
     * @param {string} [xSecretToken] 
     * @param {string} [authorization] 
     * @param {string} [ehelplyActiveParticipant] 
     * @param {string} [ehelplyProject] 
     * @param {string} [ehelplyData] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LoggingApiInterface
     */
    getServiceLogsLoggingLogsServicesServiceGetRaw(requestParameters: GetServiceLogsLoggingLogsServicesServiceGetRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<any>>;

    /**
     * Get Service Logs
     */
    getServiceLogsLoggingLogsServicesServiceGet(requestParameters: GetServiceLogsLoggingLogsServicesServiceGetRequest, initOverrides?: RequestInit): Promise<any>;

    /**
     * 
     * @summary Get Subject Logs
     * @param {string} service 
     * @param {string} subject 
     * @param {string} [dateStart] 
     * @param {string} [dateEnd] 
     * @param {boolean} [desc] 
     * @param {number} [limit] 
     * @param {string} [xAccessToken] 
     * @param {string} [xSecretToken] 
     * @param {string} [authorization] 
     * @param {string} [ehelplyActiveParticipant] 
     * @param {string} [ehelplyProject] 
     * @param {string} [ehelplyData] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LoggingApiInterface
     */
    getSubjectLogsLoggingLogsServicesServiceSubjectsSubjectGetRaw(requestParameters: GetSubjectLogsLoggingLogsServicesServiceSubjectsSubjectGetRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<any>>;

    /**
     * Get Subject Logs
     */
    getSubjectLogsLoggingLogsServicesServiceSubjectsSubjectGet(requestParameters: GetSubjectLogsLoggingLogsServicesServiceSubjectsSubjectGetRequest, initOverrides?: RequestInit): Promise<any>;

}

/**
 * 
 */
export class LoggingApi extends runtime.BaseAPI implements LoggingApiInterface {

    /**
     * Get Logs
     */
    async getLogsLoggingLogsGetRaw(requestParameters: GetLogsLoggingLogsGetRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<any>> {
        const queryParameters: any = {};

        if (requestParameters.service !== undefined) {
            queryParameters['service'] = requestParameters.service;
        }

        if (requestParameters.dateStart !== undefined) {
            queryParameters['date_start'] = requestParameters.dateStart;
        }

        if (requestParameters.dateEnd !== undefined) {
            queryParameters['date_end'] = requestParameters.dateEnd;
        }

        if (requestParameters.desc !== undefined) {
            queryParameters['desc'] = requestParameters.desc;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters.xAccessToken !== undefined && requestParameters.xAccessToken !== null) {
            headerParameters['x-access-token'] = String(requestParameters.xAccessToken);
        }

        if (requestParameters.xSecretToken !== undefined && requestParameters.xSecretToken !== null) {
            headerParameters['x-secret-token'] = String(requestParameters.xSecretToken);
        }

        if (requestParameters.authorization !== undefined && requestParameters.authorization !== null) {
            headerParameters['authorization'] = String(requestParameters.authorization);
        }

        if (requestParameters.ehelplyActiveParticipant !== undefined && requestParameters.ehelplyActiveParticipant !== null) {
            headerParameters['ehelply-active-participant'] = String(requestParameters.ehelplyActiveParticipant);
        }

        if (requestParameters.ehelplyProject !== undefined && requestParameters.ehelplyProject !== null) {
            headerParameters['ehelply-project'] = String(requestParameters.ehelplyProject);
        }

        if (requestParameters.ehelplyData !== undefined && requestParameters.ehelplyData !== null) {
            headerParameters['ehelply-data'] = String(requestParameters.ehelplyData);
        }

        const response = await this.request({
            path: `/sam/logging/logs`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.TextApiResponse(response) as any;
    }

    /**
     * Get Logs
     */
    async getLogsLoggingLogsGet(requestParameters: GetLogsLoggingLogsGetRequest = {}, initOverrides?: RequestInit): Promise<any> {
        const response = await this.getLogsLoggingLogsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Service Logs
     */
    async getServiceLogsLoggingLogsServicesServiceGetRaw(requestParameters: GetServiceLogsLoggingLogsServicesServiceGetRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<any>> {
        if (requestParameters.service === null || requestParameters.service === undefined) {
            throw new runtime.RequiredError('service','Required parameter requestParameters.service was null or undefined when calling getServiceLogsLoggingLogsServicesServiceGet.');
        }

        const queryParameters: any = {};

        if (requestParameters.dateStart !== undefined) {
            queryParameters['date_start'] = requestParameters.dateStart;
        }

        if (requestParameters.dateEnd !== undefined) {
            queryParameters['date_end'] = requestParameters.dateEnd;
        }

        if (requestParameters.desc !== undefined) {
            queryParameters['desc'] = requestParameters.desc;
        }

        if (requestParameters.limit !== undefined) {
            queryParameters['limit'] = requestParameters.limit;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters.xAccessToken !== undefined && requestParameters.xAccessToken !== null) {
            headerParameters['x-access-token'] = String(requestParameters.xAccessToken);
        }

        if (requestParameters.xSecretToken !== undefined && requestParameters.xSecretToken !== null) {
            headerParameters['x-secret-token'] = String(requestParameters.xSecretToken);
        }

        if (requestParameters.authorization !== undefined && requestParameters.authorization !== null) {
            headerParameters['authorization'] = String(requestParameters.authorization);
        }

        if (requestParameters.ehelplyActiveParticipant !== undefined && requestParameters.ehelplyActiveParticipant !== null) {
            headerParameters['ehelply-active-participant'] = String(requestParameters.ehelplyActiveParticipant);
        }

        if (requestParameters.ehelplyProject !== undefined && requestParameters.ehelplyProject !== null) {
            headerParameters['ehelply-project'] = String(requestParameters.ehelplyProject);
        }

        if (requestParameters.ehelplyData !== undefined && requestParameters.ehelplyData !== null) {
            headerParameters['ehelply-data'] = String(requestParameters.ehelplyData);
        }

        const response = await this.request({
            path: `/sam/logging/logs/services/{service}`.replace(`{${"service"}}`, encodeURIComponent(String(requestParameters.service))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.TextApiResponse(response) as any;
    }

    /**
     * Get Service Logs
     */
    async getServiceLogsLoggingLogsServicesServiceGet(requestParameters: GetServiceLogsLoggingLogsServicesServiceGetRequest, initOverrides?: RequestInit): Promise<any> {
        const response = await this.getServiceLogsLoggingLogsServicesServiceGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Subject Logs
     */
    async getSubjectLogsLoggingLogsServicesServiceSubjectsSubjectGetRaw(requestParameters: GetSubjectLogsLoggingLogsServicesServiceSubjectsSubjectGetRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<any>> {
        if (requestParameters.service === null || requestParameters.service === undefined) {
            throw new runtime.RequiredError('service','Required parameter requestParameters.service was null or undefined when calling getSubjectLogsLoggingLogsServicesServiceSubjectsSubjectGet.');
        }

        if (requestParameters.subject === null || requestParameters.subject === undefined) {
            throw new runtime.RequiredError('subject','Required parameter requestParameters.subject was null or undefined when calling getSubjectLogsLoggingLogsServicesServiceSubjectsSubjectGet.');
        }

        const queryParameters: any = {};

        if (requestParameters.dateStart !== undefined) {
            queryParameters['date_start'] = requestParameters.dateStart;
        }

        if (requestParameters.dateEnd !== undefined) {
            queryParameters['date_end'] = requestParameters.dateEnd;
        }

        if (requestParameters.desc !== undefined) {
            queryParameters['desc'] = requestParameters.desc;
        }

        if (requestParameters.limit !== undefined) {
            queryParameters['limit'] = requestParameters.limit;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters.xAccessToken !== undefined && requestParameters.xAccessToken !== null) {
            headerParameters['x-access-token'] = String(requestParameters.xAccessToken);
        }

        if (requestParameters.xSecretToken !== undefined && requestParameters.xSecretToken !== null) {
            headerParameters['x-secret-token'] = String(requestParameters.xSecretToken);
        }

        if (requestParameters.authorization !== undefined && requestParameters.authorization !== null) {
            headerParameters['authorization'] = String(requestParameters.authorization);
        }

        if (requestParameters.ehelplyActiveParticipant !== undefined && requestParameters.ehelplyActiveParticipant !== null) {
            headerParameters['ehelply-active-participant'] = String(requestParameters.ehelplyActiveParticipant);
        }

        if (requestParameters.ehelplyProject !== undefined && requestParameters.ehelplyProject !== null) {
            headerParameters['ehelply-project'] = String(requestParameters.ehelplyProject);
        }

        if (requestParameters.ehelplyData !== undefined && requestParameters.ehelplyData !== null) {
            headerParameters['ehelply-data'] = String(requestParameters.ehelplyData);
        }

        const response = await this.request({
            path: `/sam/logging/logs/services/{service}/subjects/{subject}`.replace(`{${"service"}}`, encodeURIComponent(String(requestParameters.service))).replace(`{${"subject"}}`, encodeURIComponent(String(requestParameters.subject))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.TextApiResponse(response) as any;
    }

    /**
     * Get Subject Logs
     */
    async getSubjectLogsLoggingLogsServicesServiceSubjectsSubjectGet(requestParameters: GetSubjectLogsLoggingLogsServicesServiceSubjectsSubjectGetRequest, initOverrides?: RequestInit): Promise<any> {
        const response = await this.getSubjectLogsLoggingLogsServicesServiceSubjectsSubjectGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
