/* tslint:disable */
/* eslint-disable */
/**
 * eHelply SDK - 1.1.93
 * eHelply SDK for SuperStack Services
 *
 * The version of the OpenAPI document: 1.1.93
 * Contact: support@ehelply.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ContactMethod
 */
export interface ContactMethod {
    /**
     * 
     * @type {string}
     * @memberof ContactMethod
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ContactMethod
     */
    value?: string;
}

export function ContactMethodFromJSON(json: any): ContactMethod {
    return ContactMethodFromJSONTyped(json, false);
}

export function ContactMethodFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContactMethod {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'value': !exists(json, 'value') ? undefined : json['value'],
    };
}

export function ContactMethodToJSON(value?: ContactMethod | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'value': value.value,
    };
}

