/* tslint:disable */
/* eslint-disable */
/**
 * eHelply SDK - 1.1.113
 * eHelply SDK for SuperStack Services
 *
 * The version of the OpenAPI document: 1.1.113
 * Contact: support@ehelply.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateProjectInvoice
 */
export interface CreateProjectInvoice {
    /**
     * 
     * @type {number}
     * @memberof CreateProjectInvoice
     */
    year: number;
    /**
     * 
     * @type {number}
     * @memberof CreateProjectInvoice
     */
    month: number;
}

export function CreateProjectInvoiceFromJSON(json: any): CreateProjectInvoice {
    return CreateProjectInvoiceFromJSONTyped(json, false);
}

export function CreateProjectInvoiceFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateProjectInvoice {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'year': json['year'],
        'month': json['month'],
    };
}

export function CreateProjectInvoiceToJSON(value?: CreateProjectInvoice | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'year': value.year,
        'month': value.month,
    };
}

