/* tslint:disable */
/* eslint-disable */
/**
 * eHelply SDK - 1.1.112
 * eHelply SDK for SuperStack Services
 *
 * The version of the OpenAPI document: 1.1.112
 * Contact: support@ehelply.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Field
 * @export
 * @interface Field
 */
export interface Field {
    /**
     * 
     * @type {object}
     * @memberof Field
     */
    type?: object;
    /**
     * 
     * @type {string}
     * @memberof Field
     */
    placeholder?: string;
    /**
     * 
     * @type {object}
     * @memberof Field
     */
    validations?: object;
    /**
     * 
     * @type {string}
     * @memberof Field
     */
    hint?: string;
    /**
     * 
     * @type {string}
     * @memberof Field
     */
    icon?: string;
    /**
     * 
     * @type {string}
     * @memberof Field
     */
    label?: string;
    /**
     * 
     * @type {object}
     * @memberof Field
     */
    options?: object;
}

export function FieldFromJSON(json: any): Field {
    return FieldFromJSONTyped(json, false);
}

export function FieldFromJSONTyped(json: any, ignoreDiscriminator: boolean): Field {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': !exists(json, 'type') ? undefined : json['type'],
        'placeholder': !exists(json, 'placeholder') ? undefined : json['placeholder'],
        'validations': !exists(json, 'validations') ? undefined : json['validations'],
        'hint': !exists(json, 'hint') ? undefined : json['hint'],
        'icon': !exists(json, 'icon') ? undefined : json['icon'],
        'label': !exists(json, 'label') ? undefined : json['label'],
        'options': !exists(json, 'options') ? undefined : json['options'],
    };
}

export function FieldToJSON(value?: Field | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'placeholder': value.placeholder,
        'validations': value.validations,
        'hint': value.hint,
        'icon': value.icon,
        'label': value.label,
        'options': value.options,
    };
}

