/* tslint:disable */
/* eslint-disable */
/**
 * eHelply SDK - 1.1.122
 * eHelply SDK for SuperStack Services
 *
 * The version of the OpenAPI document: 1.1.122
 * Contact: support@ehelply.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ServiceSuperStackMetaGettingStartedEndpointTeaser,
    ServiceSuperStackMetaGettingStartedEndpointTeaserFromJSON,
    ServiceSuperStackMetaGettingStartedEndpointTeaserFromJSONTyped,
    ServiceSuperStackMetaGettingStartedEndpointTeaserToJSON,
} from './ServiceSuperStackMetaGettingStartedEndpointTeaser';

/**
 * 
 * @export
 * @interface ServiceSuperStackMetaGettingStarted
 */
export interface ServiceSuperStackMetaGettingStarted {
    /**
     * 
     * @type {string}
     * @memberof ServiceSuperStackMetaGettingStarted
     */
    blurb: string;
    /**
     * 
     * @type {Array<ServiceSuperStackMetaGettingStartedEndpointTeaser>}
     * @memberof ServiceSuperStackMetaGettingStarted
     */
    endpointTeasers: Array<ServiceSuperStackMetaGettingStartedEndpointTeaser>;
}

export function ServiceSuperStackMetaGettingStartedFromJSON(json: any): ServiceSuperStackMetaGettingStarted {
    return ServiceSuperStackMetaGettingStartedFromJSONTyped(json, false);
}

export function ServiceSuperStackMetaGettingStartedFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServiceSuperStackMetaGettingStarted {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'blurb': json['blurb'],
        'endpointTeasers': ((json['endpoint_teasers'] as Array<any>).map(ServiceSuperStackMetaGettingStartedEndpointTeaserFromJSON)),
    };
}

export function ServiceSuperStackMetaGettingStartedToJSON(value?: ServiceSuperStackMetaGettingStarted | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'blurb': value.blurb,
        'endpoint_teasers': ((value.endpointTeasers as Array<any>).map(ServiceSuperStackMetaGettingStartedEndpointTeaserToJSON)),
    };
}

