/* tslint:disable */
/* eslint-disable */
/**
 * eHelply SDK - 1.1.120
 * eHelply SDK for SuperStack Services
 *
 * The version of the OpenAPI document: 1.1.120
 * Contact: support@ehelply.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ServiceSuperStackMetaFeature
 */
export interface ServiceSuperStackMetaFeature {
    /**
     * 
     * @type {string}
     * @memberof ServiceSuperStackMetaFeature
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ServiceSuperStackMetaFeature
     */
    summary: string;
}

export function ServiceSuperStackMetaFeatureFromJSON(json: any): ServiceSuperStackMetaFeature {
    return ServiceSuperStackMetaFeatureFromJSONTyped(json, false);
}

export function ServiceSuperStackMetaFeatureFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServiceSuperStackMetaFeature {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'summary': json['summary'],
    };
}

export function ServiceSuperStackMetaFeatureToJSON(value?: ServiceSuperStackMetaFeature | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'summary': value.summary,
    };
}

