/* tslint:disable */
/* eslint-disable */
/**
 * eHelply SDK
 * eHelply SDK
 *
 * The version of the OpenAPI document: 1.1.31
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Used for DB row entry
 * @export
 * @interface AccessRoleDB
 */
export interface AccessRoleDB {
    /**
     * 
     * @type {string}
     * @memberof AccessRoleDB
     */
    'uuid': string;
    /**
     * 
     * @type {string}
     * @memberof AccessRoleDB
     */
    'partition_identifier': string;
    /**
     * 
     * @type {string}
     * @memberof AccessRoleDB
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof AccessRoleDB
     */
    'summary': string;
    /**
     * 
     * @type {string}
     * @memberof AccessRoleDB
     */
    'created_at': string;
}

