/* tslint:disable */
/* eslint-disable */
/**
 * eHelply SDK
 * eHelply SDK
 *
 * The version of the OpenAPI document: 1.1.32
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Used for update endpoint
 * @export
 * @interface AccessTypeUpdate
 */
export interface AccessTypeUpdate {
    /**
     * 
     * @type {string}
     * @memberof AccessTypeUpdate
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof AccessTypeUpdate
     */
    'summary'?: string;
}

