/* tslint:disable */
/* eslint-disable */
/**
 * eHelply SDK - 1.1.73
 * eHelply SDK for SuperStack Services
 *
 * The version of the OpenAPI document: 1.1.73
 * Contact: support@ehelply.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * **:param** address_type                        **type:** string or None  **:param** address_line_1                      **type:** string or None  **:param** address_line_2                      **type:** string or None  **:param** postal_zip_code                     **type:** string or None  **:param** city                                **type:** string or None  **:param** province_state                      **type:** string or None  **:param** country                             **type:** string or None  **:param** lat                                 **type:** string or None  **:param** lng                                 **type:** string or None
 * @export
 * @interface AddressBase
 */
export interface AddressBase {
    /**
     * 
     * @type {string}
     * @memberof AddressBase
     */
    'address_type'?: string;
    /**
     * 
     * @type {string}
     * @memberof AddressBase
     */
    'address_line_1'?: string;
    /**
     * 
     * @type {string}
     * @memberof AddressBase
     */
    'address_line_2'?: string;
    /**
     * 
     * @type {string}
     * @memberof AddressBase
     */
    'postal_zip_code'?: string;
    /**
     * 
     * @type {string}
     * @memberof AddressBase
     */
    'city'?: string;
    /**
     * 
     * @type {string}
     * @memberof AddressBase
     */
    'province_state'?: string;
    /**
     * 
     * @type {string}
     * @memberof AddressBase
     */
    'country'?: string;
    /**
     * 
     * @type {string}
     * @memberof AddressBase
     */
    'lat'?: string;
    /**
     * 
     * @type {string}
     * @memberof AddressBase
     */
    'lng'?: string;
}

