/* tslint:disable */
/* eslint-disable */
/**
 * eHelply SDK - 1.1.87
 * eHelply SDK for SuperStack Services
 *
 * The version of the OpenAPI document: 1.1.87
 * Contact: support@ehelply.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AttachPaymentToProject
 */
export interface AttachPaymentToProject {
    /**
     * 
     * @type {string}
     * @memberof AttachPaymentToProject
     */
    'payment_type': string;
    /**
     * 
     * @type {string}
     * @memberof AttachPaymentToProject
     */
    'number': string;
    /**
     * 
     * @type {number}
     * @memberof AttachPaymentToProject
     */
    'exp_month': number;
    /**
     * 
     * @type {number}
     * @memberof AttachPaymentToProject
     */
    'exp_year': number;
    /**
     * 
     * @type {string}
     * @memberof AttachPaymentToProject
     */
    'cvc': string;
}

