/* tslint:disable */
/* eslint-disable */
/**
 * eHelply SDK - 1.1.87
 * eHelply SDK for SuperStack Services
 *
 * The version of the OpenAPI document: 1.1.87
 * Contact: support@ehelply.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { SecurityCreateToken } from './security-create-token';

/**
 * 
 * @export
 * @interface BodyGenerateTokenSecurityTokensPost
 */
export interface BodyGenerateTokenSecurityTokensPost {
    /**
     * 
     * @type {SecurityCreateToken}
     * @memberof BodyGenerateTokenSecurityTokensPost
     */
    'token': SecurityCreateToken;
}

