/* tslint:disable */
/* eslint-disable */
/**
 * eHelply SDK - 1.1.72
 * eHelply SDK for SuperStack Services
 *
 * The version of the OpenAPI document: 1.1.72
 * Contact: support@ehelply.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { AlarmTerminate } from './alarm-terminate';

/**
 * 
 * @export
 * @interface BodyTerminateAlarmMonitorServicesServiceStagesStageAlarmsAlarmUuidTerminatePost
 */
export interface BodyTerminateAlarmMonitorServicesServiceStagesStageAlarmsAlarmUuidTerminatePost {
    /**
     * 
     * @type {AlarmTerminate}
     * @memberof BodyTerminateAlarmMonitorServicesServiceStagesStageAlarmsAlarmUuidTerminatePost
     */
    'terminate': AlarmTerminate;
}

