/* tslint:disable */
/* eslint-disable */
/**
 * eHelply SDK
 * eHelply SDK
 *
 * The version of the OpenAPI document: 1.1.32
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { AccessRoleUpdate } from './access-role-update';

/**
 * 
 * @export
 * @interface BodyUpdateRoleAccessPartitionsPartitionIdentifierRolesRoleUuidPut
 */
export interface BodyUpdateRoleAccessPartitionsPartitionIdentifierRolesRoleUuidPut {
    /**
     * 
     * @type {AccessRoleUpdate}
     * @memberof BodyUpdateRoleAccessPartitionsPartitionIdentifierRolesRoleUuidPut
     */
    'role': AccessRoleUpdate;
}

