/* tslint:disable */
/* eslint-disable */
/**
 * eHelply SDK
 * eHelply SDK
 *
 * The version of the OpenAPI document: 1.1.31
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { AccessTypeCreate } from './access-type-create';

/**
 * 
 * @export
 * @interface BodyCreateTypeAccessPartitionsPartitionIdentifierPermissionsTypesPost
 */
export interface BodyCreateTypeAccessPartitionsPartitionIdentifierPermissionsTypesPost {
    /**
     * 
     * @type {AccessTypeCreate}
     * @memberof BodyCreateTypeAccessPartitionsPartitionIdentifierPermissionsTypesPost
     */
    'partition_type': AccessTypeCreate;
}

