/* tslint:disable */
/* eslint-disable */
/**
 * eHelply SDK - 1.1.73
 * eHelply SDK for SuperStack Services
 *
 * The version of the OpenAPI document: 1.1.73
 * Contact: support@ehelply.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * **:param** name                                **type:** string **:param** meta                                **type:** dict or None  **:param** project_uuid                        **type:** string or None
 * @export
 * @interface CategoryBase
 */
export interface CategoryBase {
    /**
     * 
     * @type {string}
     * @memberof CategoryBase
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof CategoryBase
     */
    'meta_uuid'?: string;
    /**
     * 
     * @type {object}
     * @memberof CategoryBase
     */
    'meta'?: object;
    /**
     * 
     * @type {string}
     * @memberof CategoryBase
     */
    'project_uuid'?: string;
}

