/* tslint:disable */
/* eslint-disable */
/**
 * eHelply SDK
 * eHelply SDK
 *
 * The version of the OpenAPI document: 1.1.32
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CloudParticipantAuthResponse
 */
export interface CloudParticipantAuthResponse {
    /**
     * 
     * @type {string}
     * @memberof CloudParticipantAuthResponse
     */
    'authorization'?: string;
    /**
     * 
     * @type {string}
     * @memberof CloudParticipantAuthResponse
     */
    'access_token'?: string;
    /**
     * 
     * @type {string}
     * @memberof CloudParticipantAuthResponse
     */
    'secret_token'?: string;
    /**
     * 
     * @type {object}
     * @memberof CloudParticipantAuthResponse
     */
    'claims'?: object;
    /**
     * 
     * @type {object}
     * @memberof CloudParticipantAuthResponse
     */
    'data'?: object;
}

