/* tslint:disable */
/* eslint-disable */
/**
 * eHelply SDK
 * eHelply SDK
 *
 * The version of the OpenAPI document: 1.1.31
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Detailed meta based on Notes
 * @export
 * @interface DetailedMeta
 */
export interface DetailedMeta {
    /**
     * 
     * @type {string}
     * @memberof DetailedMeta
     */
    'summary_uuid'?: string;
    /**
     * 
     * @type {string}
     * @memberof DetailedMeta
     */
    'description_uuid'?: string;
}

