/* tslint:disable */
/* eslint-disable */
/**
 * eHelply SDK - 1.1.87
 * eHelply SDK for SuperStack Services
 *
 * The version of the OpenAPI document: 1.1.87
 * Contact: support@ehelply.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Options } from './options';
import { Validations } from './validations';

/**
 * Field Dynamo
 * @export
 * @interface FieldDynamo
 */
export interface FieldDynamo {
    /**
     * 
     * @type {string}
     * @memberof FieldDynamo
     */
    'uuid': string;
    /**
     * 
     * @type {number}
     * @memberof FieldDynamo
     */
    'type'?: number;
    /**
     * 
     * @type {string}
     * @memberof FieldDynamo
     */
    'placeholder'?: string;
    /**
     * 
     * @type {Validations}
     * @memberof FieldDynamo
     */
    'validations'?: Validations;
    /**
     * 
     * @type {string}
     * @memberof FieldDynamo
     */
    'hint'?: string;
    /**
     * 
     * @type {string}
     * @memberof FieldDynamo
     */
    'icon'?: string;
    /**
     * 
     * @type {string}
     * @memberof FieldDynamo
     */
    'label'?: string;
    /**
     * 
     * @type {Options}
     * @memberof FieldDynamo
     */
    'options'?: Options;
}

