/* tslint:disable */
/* eslint-disable */
/**
 * eHelply SDK - 1.1.87
 * eHelply SDK for SuperStack Services
 *
 * The version of the OpenAPI document: 1.1.87
 * Contact: support@ehelply.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { NoteDynamo } from './note-dynamo';
import { NoteMeta } from './note-meta';

/**
 * A note from Dynamo DB including n amount of version history of that note
 * @export
 * @interface NoteDynamoHistory
 */
export interface NoteDynamoHistory {
    /**
     * 
     * @type {string}
     * @memberof NoteDynamoHistory
     */
    'uuid': string;
    /**
     * 
     * @type {any}
     * @memberof NoteDynamoHistory
     */
    'content'?: any;
    /**
     * 
     * @type {string}
     * @memberof NoteDynamoHistory
     */
    'time': string;
    /**
     * 
     * @type {NoteMeta}
     * @memberof NoteDynamoHistory
     */
    'meta': NoteMeta;
    /**
     * 
     * @type {Array<NoteDynamo>}
     * @memberof NoteDynamoHistory
     */
    'history'?: Array<NoteDynamo>;
}

