/* tslint:disable */
/* eslint-disable */
/**
 * eHelply SDK
 * eHelply SDK
 *
 * The version of the OpenAPI document: 1.1.31
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { NoteMeta } from './note-meta';

/**
 * Note This is used as the payload to endpoints
 * @export
 * @interface NoteBase
 */
export interface NoteBase {
    /**
     * 
     * @type {string}
     * @memberof NoteBase
     */
    'content': string;
    /**
     * 
     * @type {string}
     * @memberof NoteBase
     */
    'time': string;
    /**
     * 
     * @type {NoteMeta}
     * @memberof NoteBase
     */
    'meta': NoteMeta;
}

