/* tslint:disable */
/* eslint-disable */
/**
 * eHelply SDK - 1.1.73
 * eHelply SDK for SuperStack Services
 *
 * The version of the OpenAPI document: 1.1.73
 * Contact: support@ehelply.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Pagination state
 * @export
 * @interface Pagination
 */
export interface Pagination {
    /**
     * 
     * @type {number}
     * @memberof Pagination
     */
    'current_page': number;
    /**
     * 
     * @type {number}
     * @memberof Pagination
     */
    'page_size': number;
    /**
     * 
     * @type {number}
     * @memberof Pagination
     */
    'total_items': number;
    /**
     * 
     * @type {number}
     * @memberof Pagination
     */
    'total_pages': number;
    /**
     * 
     * @type {boolean}
     * @memberof Pagination
     */
    'has_previous_page': boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Pagination
     */
    'has_next_page': boolean;
    /**
     * 
     * @type {number}
     * @memberof Pagination
     */
    'previous_page'?: number;
    /**
     * 
     * @type {number}
     * @memberof Pagination
     */
    'next_page'?: number;
}

