/* tslint:disable */
/* eslint-disable */
/**
 * eHelply SDK
 * eHelply SDK
 *
 * The version of the OpenAPI document: 1.1.31
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { ProjectsUsageTypeUnitPrice } from './projects-usage-type-unit-price';

/**
 * Used for DB row entry
 * @export
 * @interface ProjectsUsageTypeDB
 */
export interface ProjectsUsageTypeDB {
    /**
     * 
     * @type {string}
     * @memberof ProjectsUsageTypeDB
     */
    'key': string;
    /**
     * 
     * @type {string}
     * @memberof ProjectsUsageTypeDB
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof ProjectsUsageTypeDB
     */
    'summary': string;
    /**
     * 
     * @type {string}
     * @memberof ProjectsUsageTypeDB
     */
    'category': string;
    /**
     * 
     * @type {string}
     * @memberof ProjectsUsageTypeDB
     */
    'service': string;
    /**
     * 
     * @type {Array<ProjectsUsageTypeUnitPrice>}
     * @memberof ProjectsUsageTypeDB
     */
    'unit_prices': Array<ProjectsUsageTypeUnitPrice>;
}

