/* tslint:disable */
/* eslint-disable */
/**
 * eHelply SDK - 1.1.87
 * eHelply SDK for SuperStack Services
 *
 * The version of the OpenAPI document: 1.1.87
 * Contact: support@ehelply.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ProjectsProjectMemberDB
 */
export interface ProjectsProjectMemberDB {
    /**
     * 
     * @type {string}
     * @memberof ProjectsProjectMemberDB
     */
    'uuid': string;
    /**
     * 
     * @type {string}
     * @memberof ProjectsProjectMemberDB
     */
    'project_uuid': string;
    /**
     * 
     * @type {string}
     * @memberof ProjectsProjectMemberDB
     */
    'entity_uuid': string;
    /**
     * 
     * @type {string}
     * @memberof ProjectsProjectMemberDB
     */
    'role': string;
    /**
     * 
     * @type {string}
     * @memberof ProjectsProjectMemberDB
     */
    'created_at': string;
}

