/* tslint:disable */
/* eslint-disable */
/**
 * eHelply SDK
 * eHelply SDK
 *
 * The version of the OpenAPI document: 1.1.30
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Used for create endpoint
 * @export
 * @interface ProjectsProjectCreate
 */
export interface ProjectsProjectCreate {
    /**
     * 
     * @type {string}
     * @memberof ProjectsProjectCreate
     */
    'name': string;
}

