/* tslint:disable */
/* eslint-disable */
/**
 * eHelply SDK
 * eHelply SDK
 *
 * The version of the OpenAPI document: 1.1.31
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Used for get endpoint
 * @export
 * @interface SecurityKeyGet
 */
export interface SecurityKeyGet {
    /**
     * 
     * @type {string}
     * @memberof SecurityKeyGet
     */
    'uuid': string;
    /**
     * 
     * @type {string}
     * @memberof SecurityKeyGet
     */
    'access': string;
    /**
     * 
     * @type {string}
     * @memberof SecurityKeyGet
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof SecurityKeyGet
     */
    'summary': string;
    /**
     * 
     * @type {string}
     * @memberof SecurityKeyGet
     */
    'created_at': string;
    /**
     * 
     * @type {string}
     * @memberof SecurityKeyGet
     */
    'last_used_at': string;
}

