/* tslint:disable */
/* eslint-disable */
/**
 * eHelply SDK - 1.1.73
 * eHelply SDK for SuperStack Services
 *
 * The version of the OpenAPI document: 1.1.73
 * Contact: support@ehelply.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Information to confirm user
 * @export
 * @interface UserConfirmation
 */
export interface UserConfirmation {
    /**
     * 
     * @type {string}
     * @memberof UserConfirmation
     */
    'email': string;
    /**
     * 
     * @type {string}
     * @memberof UserConfirmation
     */
    'verification_code': string;
}

