/* tslint:disable */
/* eslint-disable */
/**
 * eHelply SDK - 1.1.87
 * eHelply SDK for SuperStack Services
 *
 * The version of the OpenAPI document: 1.1.87
 * Contact: support@ehelply.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Information for resetting the new password with a confirmation code
 * @export
 * @interface UserPasswordResetConfirmation
 */
export interface UserPasswordResetConfirmation {
    /**
     * 
     * @type {string}
     * @memberof UserPasswordResetConfirmation
     */
    'email': string;
    /**
     * 
     * @type {string}
     * @memberof UserPasswordResetConfirmation
     */
    'confirmation_code': string;
    /**
     * 
     * @type {string}
     * @memberof UserPasswordResetConfirmation
     */
    'password': string;
}

