/* tslint:disable */
/* eslint-disable */
/**
 * eHelply SDK - 1.1.73
 * eHelply SDK for SuperStack Services
 *
 * The version of the OpenAPI document: 1.1.73
 * Contact: support@ehelply.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * User information used for user signup
 * @export
 * @interface UserSignup
 */
export interface UserSignup {
    /**
     * 
     * @type {string}
     * @memberof UserSignup
     */
    'username': string;
    /**
     * 
     * @type {string}
     * @memberof UserSignup
     */
    'password': string;
    /**
     * 
     * @type {string}
     * @memberof UserSignup
     */
    'email': string;
    /**
     * 
     * @type {string}
     * @memberof UserSignup
     */
    'first_name': string;
    /**
     * 
     * @type {string}
     * @memberof UserSignup
     */
    'last_name': string;
    /**
     * 
     * @type {string}
     * @memberof UserSignup
     */
    'phone_number': string;
    /**
     * 
     * @type {string}
     * @memberof UserSignup
     */
    'country': string;
    /**
     * 
     * @type {string}
     * @memberof UserSignup
     */
    'lat'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserSignup
     */
    'lng'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof UserSignup
     */
    'verified_legal_terms'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof UserSignup
     */
    'picture'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof UserSignup
     */
    'newsletters'?: boolean;
}

